name: Run tests
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 17
    steps:
      - uses: actions/checkout@master
      - name: Setup java 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: mvn -f test-app/pom.xml test
